---
{{- if eq "true" .Values.createDeepfenceKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: deepfence-key
  labels:
    {{- include "deepfence-agent.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- if .Values.deepfenceKey }}
  deepfence-key: "{{ .Values.deepfenceKey | b64enc }}"
{{- else }}
  deepfence-key: ""
{{- end }}
{{- end }}
---